// Team Tactic cards with their current tournament legality status (Legal / Restricted / Banned).
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.teamTactics = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  return [
    { name: 'Avengers Assemble', status: 'Legal' },
    { name: 'Brace for Impact', status: 'Restricted' },
    { name: 'Cosmic Invigoration', status: 'Legal' },
    { name: 'Dark Reign', status: 'Legal' },
    { name: 'Disarm', status: 'Banned' },
    { name: 'Drop Off', status: 'Banned' },
    { name: 'Escort to Safety', status: 'Banned' },
    { name: 'Follow Me', status: 'Banned' },
    { name: 'Heave Ho', status: 'Banned' },
    { name: 'Inspiring Monologue', status: 'Banned' },
    { name: 'Mission Objective', status: 'Banned' },
    { name: 'One-Two Punch', status: 'Banned' },
    { name: 'Patch Up', status: 'Restricted' },
    { name: 'Ricochet Blast', status: 'Legal' },
    { name: 'Sacrifice', status: 'Restricted' },
    { name: 'Second Wind', status: 'Legal' },
    { name: 'Smash', status: 'Banned' },
    { name: 'Sucker', status: 'Banned' },
    { name: 'The Age of Ultron', status: 'Banned' },
    { name: 'Trip Up', status: 'Banned' },
    { name: 'Anger Management', status: 'Legal' },
    { name: 'Gamma Launch', status: 'Legal' },
    { name: 'Seeing Red', status: 'Banned' },
    { name: 'A.I.M. Lackeys', status: 'Banned' },
    { name: 'Psychic Fortress', status: 'Legal' },
    { name: 'Recalibration Matrix', status: 'Legal' },
    { name: 'Battle Lust', status: 'Banned' },
    { name: 'Usurp the Throne', status: 'Legal' },
    { name: 'Wakanda Forever', status: 'Legal' },
    { name: 'Advanced R&D', status: 'Banned' },
    { name: 'Vibranium Shielding', status: 'Legal' },
    { name: 'Lethal Protector', status: 'Legal' },
    { name: 'Uneasy Allies', status: 'Legal' },
    { name: 'All Webbed Up', status: 'Legal' },
    { name: 'All You\'ve Got', status: 'Banned' },
    { name: 'Web Barrier', status: 'Banned' },
    { name: 'Odin\'s Blessing', status: 'Legal' },
    { name: 'Thunderwave', status: 'Legal' },
    { name: 'Doomed Prophecy', status: 'Legal' },
    { name: 'Sibling Rivalry', status: 'Legal' },
    { name: 'Field Dressing', status: 'Banned' },
    { name: 'Psychic Shielding Device (P.S.D.)', status: 'Banned' },
    { name: 'Tactical Analysis', status: 'Banned' },
    { name: 'Till the End of the Line', status: 'Legal' },
    { name: 'Blood to Spare', status: 'Legal' },
    { name: 'Execute', status: 'Legal' },
    { name: 'Price of Failure', status: 'Legal' },
    { name: 'Daughters of Thanos', status: 'Legal' },
    { name: 'Medpack', status: 'Banned' },
    { name: 'Deadly Duo', status: 'Legal' },
    { name: 'We Are Groot', status: 'Legal' },
    { name: 'Crew of the Milano', status: 'Banned' },
    { name: 'Rocket Boots?!', status: 'Banned' },
    { name: 'Marked for Death', status: 'Banned' },
    { name: 'Mothership', status: 'Legal' },
    { name: 'Shhh...', status: 'Legal' },
    { name: 'No Matter the Cost', status: 'Banned' },
    { name: 'Unearthly Rage', status: 'Banned' },
    { name: 'Blind Obsession', status: 'Banned' },
    { name: 'Well-Laid Plans', status: 'Legal' },
    { name: 'Pentagram of Farallah', status: 'Legal' },
    { name: 'Seven Suns of Cinnibus', status: 'Legal' },
    { name: 'Vapors of Valtorr', status: 'Legal' },
    { name: 'Heavy Firepower', status: 'Legal' },
    { name: 'Professionals', status: 'Legal' },
    { name: 'Face Me', status: 'Banned' },
    { name: 'Power of the Cosmos', status: 'Legal' },
    { name: 'No Escape', status: 'Banned' },
    { name: 'Pym Particles', status: 'Legal' },
    { name: 'Reversal', status: 'Banned' },
    { name: 'Deal With the Devil', status: 'Legal' },
    { name: 'Highway to Hell', status: 'Legal' },
    { name: 'Grievous Wounds', status: 'Legal' },
    { name: 'Lovable Misfits', status: 'Legal' },
    { name: 'Rainbow Bridge', status: 'Legal' },
    { name: 'All According To Plan', status: 'Legal' },
    { name: 'Hired Muscle', status: 'Banned' },
    { name: 'Shadow Organization', status: 'Legal' },
    { name: 'Acute Senses', status: 'Banned' },
    { name: 'Climbing Gear', status: 'Banned' },
    { name: 'Cruelty', status: 'Legal' },
    { name: 'Heavy Ordinance', status: 'Banned' },
    { name: 'Blood Red and Personal', status: 'Legal' },
    { name: 'Extreme Conditioning', status: 'Banned' },
    { name: 'Dark Empowerment', status: 'Legal' },
    { name: 'Dark Restoration', status: 'Legal' },
    { name: 'Attilan Rising', status: 'Legal' },
    { name: 'Inhuman Royal Family', status: 'Legal' },
    { name: 'Terrigenesis', status: 'Legal' },
    { name: 'Bitter Rivals', status: 'Banned' },
    { name: 'Elemental Infusion', status: 'Legal' },
    { name: 'Last-Minute Save', status: 'Legal' },
    { name: 'Aunt May\'s Wheat Cakes', status: 'Legal' },
    { name: 'Spider-Tracker', status: 'Legal' },
    { name: 'The Cat and the Spider', status: 'Legal' },
    { name: 'Bird of Prey', status: 'Legal' },
    { name: 'Eyes on the Prize', status: 'Banned' },
    { name: 'Tactical Maneuvers', status: 'Banned' },
    { name: 'The Air Force', status: 'Legal' },
    { name: 'A-Force Assemble!', status: 'Legal' },
    { name: 'Agents of S.M.A.S.H.', status: 'Legal' },
    { name: 'Special Delivery', status: 'Legal' },
    { name: 'Stalwart Determination', status: 'Legal' },
    { name: 'Weapon X Program', status: 'Legal' },
    { name: 'X-Ceptional Healing', status: 'Banned' },
    { name: 'Children of the Atom', status: 'Legal' },
    { name: 'First Class', status: 'Legal' },
    { name: 'To Me My X-Men', status: 'Legal' },
    { name: 'Asteroid M', status: 'Legal' },
    { name: 'Magnetic Crush', status: 'Legal' },
    { name: 'Magnetic Refraction', status: 'Legal' },
    { name: 'Deception', status: 'Banned' },
    { name: 'The Books of Truth', status: 'Legal' },
    { name: 'Chimichangas', status: 'Legal' },
    { name: 'Pretty Sneaky, Sis', status: 'Legal' },
    { name: 'Yoink', status: 'Legal' },
    { name: 'Cloning Banks', status: 'Legal' },
    { name: 'Forced Extraction', status: 'Legal' },
    { name: 'Cat and Mouse', status: 'Legal' },
    { name: 'Dirty Work', status: 'Legal' },
    { name: 'Warpath', status: 'Legal' },
    { name: 'Banishment', status: 'Legal' },
    { name: 'Bats the Ghost Hound', status: 'Legal' },
    { name: 'Siege of Darkness', status: 'Legal' },
    { name: 'Heroes for Hire', status: 'Legal' },
    { name: 'K\'un-Lun Training', status: 'Banned' },
    { name: 'Kick \'em While They\'re Down', status: 'Banned' },
    { name: 'Carnage Rules', status: 'Legal' },
    { name: 'The Grand Illusion', status: 'Legal' },
    { name: 'There Will Be Carnage', status: 'Legal' },
    { name: 'Directive One', status: 'Legal' },
    { name: 'Efficient Machines', status: 'Legal' },
    { name: 'Scrap Metal', status: 'Legal' },
    { name: 'Fall Back', status: 'Restricted' },
    { name: 'Helios Laser Bombardment', status: 'Legal' },
    { name: 'Jean!!!', status: 'Legal' },
    { name: 'Mental Domination', status: 'Legal' },
    { name: 'Carbonadium Synthesizer', status: 'Legal' },
    { name: 'Red Room Training', status: 'Banned' },
    { name: 'Battlefield Medicine', status: 'Legal' },
    { name: 'Defensive Prototype', status: 'Legal' },
    { name: 'Eye In The Sky', status: 'Legal' },
    { name: 'Hard Reset', status: 'Legal' },
    { name: 'Helicarrier Strike', status: 'Legal' },
    { name: 'Life Model Decoy', status: 'Legal' },
    { name: 'Reposition', status: 'Legal' },
    { name: 'Sitrep', status: 'Legal' },
    { name: 'The Initiative', status: 'Legal' },
    { name: 'The Shieldmobile', status: 'Legal' },
    { name: 'Do You Know Who I Am?', status: 'Legal' },
    { name: 'Makin\' A Ruckus', status: 'Legal' },
    { name: 'Versatile Strategy', status: 'Legal' },
    { name: 'Fastball Special!', status: 'Legal' },
    { name: 'Indomitable', status: 'Restricted' },
    { name: 'Journey Through Limbo', status: 'Legal' },
    { name: 'Fearful Symmetry', status: 'Legal' },
    { name: 'Monkey Brain Is Lizard Home', status: 'Legal' },
    { name: 'Neogenetic Recombinator', status: 'Legal' },
    { name: 'Sinister Traps', status: 'Legal' },
    { name: 'Charming Thief', status: 'Legal' },
    { name: 'Dark Past', status: 'Legal' },
    { name: 'Mind If I Cut In?', status: 'Legal' },
    { name: 'Pardon Me, Sugah', status: 'Legal' },
    { name: 'Illicit Tech', status: 'Legal' },
    { name: 'To Ash and Cinder', status: 'Legal' },
    { name: 'A Better Tomorrow', status: 'Legal' },
    { name: 'Fan Club', status: 'Legal' },
    { name: 'Can I Borrow That?', status: 'Legal' },
    { name: 'Difficult To Please', status: 'Legal' },
    { name: 'No More Mutants', status: 'Legal' },
    { name: 'The Whims of Chaos', status: 'Legal' },
    { name: 'Astral Ring', status: 'Legal' },
    { name: 'Bane of Damballah', status: 'Legal' },
    { name: 'Orb of Agamotto', status: 'Legal' },
    { name: 'Hood\'s Gang', status: 'Legal' },
    { name: 'Plane of Pohldahk', status: 'Legal' },
    { name: 'Seance', status: 'Legal' },
    { name: 'Book of Cagliostro', status: 'Legal' },
    { name: 'Iron-Bound Books of Shuma-Gorath', status: 'Legal' },
    { name: 'Wand of Watoomb', status: 'Legal' },
    { name: 'The Bar With No Doors', status: 'Legal' },
    { name: 'Cover Me', status: 'Legal' },
    { name: 'Sable International', status: 'Legal' },
    { name: 'Street Smarts', status: 'Legal' },
    { name: 'Jonathan the Unstoppable', status: 'Legal' },
    { name: 'Wolverines', status: 'Legal' },
    { name: 'Endless Legions', status: 'Legal' },
    { name: 'Inevitable Betrayal', status: 'Legal' },
    { name: 'Occult Research', status: 'Legal' },
    { name: 'Sleeper Agent', status: 'Legal' },
    { name: 'Two More Shall Rise', status: 'Legal' },
    { name: 'Victory Assured', status: 'Legal' },
    { name: 'World Domination', status: 'Legal' },
    { name: 'Infiltration', status: 'Legal' },
    { name: 'Over The Top', status: 'Legal' },
    { name: 'Scientific Method', status: 'Legal' },
    { name: 'The High Council', status: 'Legal' },
    { name: 'A New Age', status: 'Legal' },
    { name: 'Bounty Hunters', status: 'Legal' },
    { name: 'Cruel Tutelage', status: 'Legal' },
    { name: 'No Mercy', status: 'Legal' },
    { name: 'Shuriken Arashi', status: 'Legal' },
    { name: 'Vendetta', status: 'Legal' },
    { name: 'Black Onslaught', status: 'Legal' },
    { name: 'First of the Black Order', status: 'Legal' },
    { name: 'Psychic Shockwave', status: 'Legal' },
    { name: 'Leapfrog', status: 'Legal' },
    { name: 'Pyrotechnics', status: 'Legal' },
    { name: 'Dark Aura Manifestation', status: 'Legal' },
    { name: 'Fusion Caster', status: 'Legal' },
    { name: 'Winter Rush', status: 'Legal' },
    { name: 'Bear Hug', status: 'Legal' },
    { name: 'Comrade\'s Keeper', status: 'Legal' },
    { name: 'Sovereign Strike', status: 'Legal' },
    { name: 'Galaxy\'s Greatest', status: 'Legal' },
    { name: 'Servants of the Titan', status: 'Legal' },
    { name: 'It\'s Time Travel... Don\'t Ask', status: 'Legal' },
    { name: 'Midnight Phantasmagoria', status: 'Legal' },
    { name: 'The Black Bifrost', status: 'Legal' },
    { name: 'Faithful Companion', status: 'Legal' },
    { name: 'Hold Still', status: 'Legal' },
    { name: 'Untapped Potential', status: 'Legal' },
    { name: 'Xavier\'s Dream', status: 'Legal' },
    { name: 'Rhino In A China Shop', status: 'Legal' },
    { name: 'This Is A Robbery', status: 'Legal' },
    { name: 'Clean Up', status: 'Legal' },
    { name: 'Double Agent', status: 'Legal' },
    { name: 'Foreign Assignment', status: 'Legal' },
    { name: 'On Patrol', status: 'Legal' },
    { name: 'Meet My Executioner', status: 'Legal' },
    { name: 'Weapons of Midgard', status: 'Legal' },
    { name: 'Crimson Dawn', status: 'Legal' },
    { name: 'Headmistress', status: 'Legal' },
    { name: 'Mind Transfer', status: 'Legal' },
    { name: 'My Hellfire Club', status: 'Legal' },
    { name: 'Psionic Constructs', status: 'Legal' },
    { name: 'Death', status: 'Legal' },
    { name: 'Famine', status: 'Legal' },
    { name: 'Master of the Horsemen', status: 'Legal' },
    { name: 'Pestilence', status: 'Legal' },
    { name: 'War', status: 'Legal' },
    { name: 'Mass Transit', status: 'Legal' },
    { name: 'Mutant Traitor', status: 'Legal' },
    { name: 'Preserve the Dream', status: 'Legal' },
    { name: 'Jabari Chieftain', status: 'Legal' },
    { name: 'Spirit of Wakanda', status: 'Legal' },
    { name: 'Supersonic Annihilator', status: 'Legal' },
    { name: 'Brothers In Arms', status: 'Banned' },
    { name: 'Rock And Troll', status: 'Legal' },
    { name: 'Skuttlebutt, On Me!', status: 'Legal' },
    { name: 'Inexplicable Demise', status: 'Legal' },
    { name: 'They Say Keep Your Enemies Close...', status: 'Legal' },
    { name: 'No, Try This One!', status: 'Legal' },
    { name: 'Repulsor Refraction', status: 'Legal' },
    { name: 'Soldat Activated', status: 'Legal' },
    { name: 'Reserve Members', status: 'Legal' },
    { name: 'Stark Armory', status: 'Legal' },
    { name: 'Joint Effort', status: 'Legal' },
    { name: 'Vertical Assistance', status: 'Legal' },
    { name: 'This Is Our Day', status: 'Legal' },
    { name: 'Battle Plan', status: 'Legal' },
    { name: 'Cosmic Obliteration', status: 'Legal' },
    { name: 'Dig In', status: 'Legal' },
    { name: 'I Am A Baron, After All', status: 'Legal' },
    { name: 'Go Get \'Em Tiger', status: 'Legal' },
    { name: 'Overcharge', status: 'Legal' },
    { name: 'Gamma Drain', status: 'Legal' },
    { name: 'One Below All', status: 'Legal' },
    { name: 'Mind Games', status: 'Legal' },
    { name: 'Simpleton! I\'ll Do It Myself!', status: 'Legal' },
    { name: 'Astral Plane', status: 'Legal' },
    { name: 'Cerebro', status: 'Legal' },
    { name: 'Mind Wipe', status: 'Legal' },
    { name: 'Clone Saga', status: 'Legal' },
    { name: 'Masked Menace', status: 'Legal' },
    { name: 'Venomized', status: 'Legal' },
    { name: 'Custom Upgrades', status: 'Legal' },
    { name: 'Founding Members', status: 'Legal' },
    { name: 'Rejuvenation', status: 'Legal' },
    { name: 'Static Arc', status: 'Legal' },
    { name: 'Strategic Retreat', status: 'Legal' },
    { name: 'Surprise, Webhead', status: 'Legal' },
    { name: 'King\'s Command', status: 'Legal' },
    { name: 'Strength and Cunning', status: 'Legal' },
    { name: 'Wisdom of the Ancestors', status: 'Legal' },
    { name: 'Online and Operational', status: 'Legal' },
    { name: 'Under Your Skin', status: 'Legal' },
    { name: 'The Bar With No Doors (Reverse)', status: 'Legal' },
    { name: 'Are You Sure You Want To Remember?', status: 'Legal' },
    { name: 'Call The Pack', status: 'Legal' },
    { name: 'Dossier', status: 'Legal' },
    { name: 'Gotta Get Some Air', status: 'Legal' },
    { name: 'Happy Birthday, Runt!', status: 'Legal' },
    { name: 'Glory Of Ultron', status: 'Legal' },
    { name: 'Bast\'s Blessing', status: 'Legal' },
    { name: 'K\'liluna\'s Glory', status: 'Legal' },
    { name: 'Synthetic Heart-Shaped Herbs', status: 'Legal' },
    { name: 'Trial By Combat', status: 'Legal' },
    { name: 'Mystic Ward', status: 'Legal' },
    { name: 'The Invaders', status: 'Legal' },
    { name: 'Prince\'s Protection', status: 'Legal' },
    { name: 'Chi Mastery', status: 'Legal' },
    { name: 'Human Weapon', status: 'Legal' },
    { name: 'For A Limited Time Only', status: 'Legal' },
    { name: 'Giant\'s Blood', status: 'Legal' },
    { name: 'Heart Of The Worthy', status: 'Legal' },
    { name: 'Trickster\'s Boon', status: 'Legal' },
    { name: 'Freyja\'s Blessing', status: 'Legal' },
    { name: 'Instant Recovery', status: 'Legal' },
    { name: 'Stolen Identity', status: 'Legal' },
    { name: 'Survive the Night', status: 'Legal' },
    { name: 'Embrace the Inferno', status: 'Legal' },
    { name: 'Brand New Day', status: 'Legal' },
    { name: 'The First One', status: 'Legal' },
    { name: 'Survival', status: 'Legal' },
    { name: 'Up The Ante', status: 'Legal' },
    { name: 'New Mutants', status: 'Legal' },
    { name: 'Tomorrow\'s Soldiers', status: 'Legal' },
    { name: 'Fallen', status: 'Legal' },
    { name: 'Ultimate Sacrifice', status: 'Legal' },
    { name: 'Implanted Memories', status: 'Legal' },
    { name: 'Weapons Stash', status: 'Legal' },
    { name: 'Immortal Servants', status: 'Legal' },
    { name: 'Battle Bound', status: 'Legal' },
    { name: 'Death From Above', status: 'Legal' },
    { name: 'Practice Round', status: 'Legal' },
    { name: 'Self-Help', status: 'Legal' },
    { name: 'Service to Anubis', status: 'Legal' },
    { name: 'Thralls of Dracula', status: 'Legal' },
    { name: 'Phases of the Moon', status: 'Legal' },
    { name: 'Hideous Monster', status: 'Legal' },
    { name: 'Devil\'s Reckoning', status: 'Legal' },
    { name: 'Gamma Burst', status: 'Legal' },
    { name: 'You Will Do As I Say, Monster', status: 'Legal' },
    { name: 'Stronger Together', status: 'Legal' },
    { name: 'Mystic Menace', status: 'Legal' },
    { name: 'Dimensional Quagmire', status: 'Legal' },
    { name: 'Call for Backup', status: 'Legal' },
    { name: 'Veterans of the Annihilation War', status: 'Legal' },
    { name: 'Covering Fire', status: 'Legal' },
    { name: 'Plundered Goods', status: 'Legal' },
    { name: 'Protector of the Empire', status: 'Legal' },
    { name: 'Praetor of the Imperial Guard', status: 'Legal' },
    { name: 'Genetic Prophecy', status: 'Legal' },
    { name: 'Inhuman Queen', status: 'Legal' },
    { name: 'Plots within Plots', status: 'Legal' },
    { name: 'Inhomo Supremis', status: 'Legal' },
    { name: 'The Great Refuge', status: 'Banned' },
    { name: 'Royal Guardians', status: 'Legal' },
    { name: 'I Am Reborn', status: 'Legal' },
    { name: 'Flames of Life', status: 'Legal' },
    { name: 'The White-Hot Room', status: 'Legal' },
    { name: 'Fault Line', status: 'Legal' },
    { name: 'Genetic Superiority', status: 'Legal' },
    { name: 'Mirage', status: 'Legal' },
    { name: 'The Pawns Go First', status: 'Legal' },
    { name: 'Caught In A Ham', status: 'Legal' },
    { name: 'Spider-Sleuth', status: 'Legal' },
    { name: 'Spider Totem: The Bride', status: 'Legal' },
    { name: 'Extreme Measures', status: 'Legal' },
    { name: 'Spider-Men', status: 'Legal' },
    { name: 'High-Tech Heist', status: 'Legal' },
    { name: 'Web of the Spider-Verse', status: 'Legal' },
    { name: 'Great Power', status: 'Legal' },
    { name: 'Brief Reprieve', status: 'Legal' },
    { name: 'Parts of a Hole', status: 'Legal' },
    { name: 'Totem of the Tiger God', status: 'Legal' },
    { name: 'The Night Life', status: 'Legal' },
    { name: 'Protege', status: 'Legal' },
    { name: 'Chronal Manipulation', status: 'Legal' },
    { name: 'Steal the Future', status: 'Legal' },
    { name: 'Going All Out', status: 'Legal' },
    { name: 'Phase Manipulation', status: 'Legal' },
    { name: 'Strange Adventures', status: 'Legal' },
    { name: 'The Man Of Marvels', status: 'Legal' },
    { name: 'The Ultimates', status: 'Legal' },
    { name: 'Deeds Worthy Of Song', status: 'Legal' },
    { name: 'Ride of the Valkyires', status: 'Legal' },
    { name: 'Warrior\'s Frenzy', status: 'Legal' },
    { name: 'Warriors\' Oath', status: 'Legal' },
    { name: 'Cosmic Awareness', status: 'Legal' },
    { name: 'Power Couple', status: 'Legal' },
    { name: 'The Magus', status: 'Legal' },
    { name: 'The Douglas Family', status: 'Legal' },
    { name: 'Data Backup', status: 'Legal' },
    { name: 'Danger Management', status: 'Legal' },
    { name: 'Guns Blazin\'', status: 'Legal' },
    { name: 'Corporate Espionage', status: 'Legal' },
    { name: 'The Best Defense', status: 'Legal' },
    { name: 'Trust No One But Yourself', status: 'Legal' },
    { name: 'A Perfect Future', status: 'Legal' },
    { name: 'Building The Mother Mold', status: 'Legal' },
    { name: 'Extinction Event', status: 'Legal' },
    { name: 'Greater Than The Sum', status: 'Legal' },
    { name: 'Know Thy Enemy', status: 'Legal' },
    { name: 'Technological Jump-Start', status: 'Legal' },
  ];
}));
